//
//  CreateOrderPresenter.swift
//  CleanSwiftTry
//
//  Created by Kaushal Elsewhere on 10/05/2017.
//  Copyright (c) 2017 Elsewhere. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateOrderPresenterInput {
    func presentPrice(resonse: CreateOrder_Price_Response)
    func presentSomething(response: CreateOrder.Something.Response)
}

protocol CreateOrderPresenterOutput: class {
    func displayPrice(viewModel: CreateOrder_Price_ViewModel)
    func displaySomething(viewModel: CreateOrder.Something.ViewModel)
}

class CreateOrderPresenter: CreateOrderPresenterInput {
  weak var output: CreateOrderPresenterOutput!
  
    // MARK: - Presentation logic
    func presentSomething(response: CreateOrder.Something.Response) {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = CreateOrder.Something.ViewModel()
        output.displaySomething(viewModel)
    }
    
    func presentPrice(resonse: CreateOrder_Price_Response) {
        let viewModel = CreateOrder_Price_ViewModel(price: "$\(resonse.price)")
        output.displayPrice(viewModel)
    }
}
