//
//  CreateOrderModels.swift
//  CleanSwiftTry
//
//  Created by Kaushal Elsewhere on 10/05/2017.
//  Copyright (c) 2017 Elsewhere. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CreateOrder
{
  struct Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}

struct CreateOrder_Price_Request {
    var selectedIndex: Int
}

struct CreateOrder_Price_Response {
    var price: Int
}

struct CreateOrder_Price_ViewModel {
    var price: String
}
