# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestGeneratedSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #pod 'AWSAPIGateway', '~> 2.4.2'
  #pod 'APIGatewayGeneratedSDK', :git => 'https://github.com/BirdCage-AU/APIGatewayGeneratedSDK.git', :tag => '0.1.0'
  
  pod 'AWSCognito' #, '~>2.5.1'

end
